part of ThreeDart.IO;

/// Entity writer for writing *.obj files.
class _objWriter {
  bool _normals;
  bool _texture;
  bool _txtCube;
  List<String> _lines = [];
  int _totalVertices = 1;
  int _decimals;

  /// Creates a new object writer.
  _objWriter(this._normals, this._texture, this._txtCube, this._decimals) {
    this._lines.add('# Generated by 3Dart');
  }

  /// Adds an entity to the object file.
  void addEntity(Core.Entity entity) {
    for(Core.Entity child in entity.children)
      this.addEntity(child);

    var shape = entity.shape;
    if (shape != null) {
      this._lines.add('o ${entity.name}');
      this.addShape(shape);
    }
  }

  /// Gets all the lines of the object file.
  List<String> get lines => this._lines;

  /// Stringifies the given double with the configured decimals.
  String _toStr(double value) {
    return value.toStringAsFixed(this._decimals);
  }

  /// Adds a shape to the object file.
  void addShape(Shapes.Shape shape) {
    final int offset = this._totalVertices;

    final int vertexCount = shape.vertices.length;
    if (this._normals) shape.calculateNormals();
    if (this._texture && this._txtCube) shape.calculateCubeTextures();
    for (int i = 0; i < vertexCount; i++) {
      Shapes.Vertex vertex = shape.vertices[i];
      this._lines.add('v '+this._toStr(vertex.location.x)+' '+this._toStr(vertex.location.y)+' '+this._toStr(vertex.location.z));
      if (this._texture) {
        if (this._txtCube)
          this._lines.add('vt '+this._toStr(vertex.textureCube.dx)+' '+this._toStr(vertex.textureCube.dy)+' '+this._toStr(vertex.textureCube.dz));
        else this._lines.add('vt '+this._toStr(vertex.texture2D.x)+' '+this._toStr(vertex.texture2D.y));
      }
      if (this._normals) this._lines.add('vn '+this._toStr(vertex.normal.dx)+' '+this._toStr(vertex.normal.dy)+' '+this._toStr(vertex.normal.dz));
    }
    this._totalVertices += vertexCount;

    final int faceCount = shape.faces.length;
    for (int i = 0; i < faceCount; i++) {
      Shapes.Face face = shape.faces[i];
      int v1 = face.vertex1.index + offset;
      int v2 = face.vertex2.index + offset;
      int v3 = face.vertex3.index + offset;
      if (this._texture) {
        if (this._normals)
          this._lines.add('f ${v1}/${v1}/${v1} ${v2}/${v2}/${v2} ${v3}/${v3}/${v3}');
        else this._lines.add('f ${v1}/${v1} ${v2}/${v2} ${v3}/${v3}');
      } else {
        if (this._normals)
          this._lines.add('f ${v1}//${v1} ${v2}//${v2} ${v3}//${v3}');
        else this._lines.add('f ${v1} ${v2} ${v3}');
      }
    }
  }
}
