library ThreeDart.Shapes;

import 'dart:typed_data' as Typed;
import 'dart:web_gl' as WebGL;
import 'dart:math';

import '../Collections/Collections.dart' as Collections;
import '../Events/Events.dart' as Events;
import '../Data/Data.dart' as Data;
import '../Debug/Debug.dart' as Debug;
import '../Math/Math.dart' as Math;
import '../Textures/Textures.dart' as Textures;

part 'BranchNode.dart';
part 'Builders.dart';
part 'Face.dart';
part 'FaceMatcher.dart';
part 'LeafNode.dart';
part 'LeafNodeVertexCollection.dart';
part 'Line.dart';
part 'LineMatcher.dart';
part 'PassNode.dart';
part 'Path.dart';
part 'Point.dart';
part 'Node.dart';
part 'Octree.dart';
part 'ReducedShape.dart';
part 'Results.dart';
part 'Shape.dart';
part 'ShapeBuilder.dart';
part 'ShapeFaceCollection.dart';
part 'ShapeLineCollection.dart';
part 'ShapePointCollection.dart';
part 'ShapeVertexCollection.dart';
part 'Vertex.dart';
part 'VertexFaceCollection.dart';
part 'VertexLineCollection.dart';
part 'VertexMatcher.dart';
part 'VertexMeasure.dart';
part 'VertexMerger.dart';
part 'VertexPointCollection.dart';
